name: Lint, test & deploy workflow
on: push
jobs:
  environment:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: copy other files
        uses: actions/checkout@v3
  lint:
    needs: environment
    runs-on: ubuntu-latest
    steps:
      - name: Lint script 
        run: npm run lint
  test:
    needs: [environment, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Test script 
        run: npm run test
  build:
    needs: [environment, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Build script 
        run: npm run build

# uses is for actions and run is for comands(eg. npm run build)