name: Lint, test & deploy workflow
on: push
jobs:
  environment:
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: copy other files
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint script 
        run: npm run lint
      - name: Test script 
        run: npm run test
      - name: Build script 
        run: npm run build

# uses is for actions and run is for comands(eg. npm run build)